package mulin.tvdy.pump;

/**
 * JS injected into the hidden douyin.com WebView. Pulled out of
 * {@link FeedPumpController} into plain string constants purely so that class
 * isn't dominated by string-building noise.
 */
final class FeedHookScripts {

    private FeedHookScripts() {
    }

    /**
     * Hooks fetch/XHR so every response the real page receives for itself
     * gets mirrored back to native code via {@code window.AndroidBridge}.
     * Idempotent (guarded by {@code window.__tvdyPumpHooked}) - safe to
     * inject from document-start, {@code onPageStarted}, and
     * {@code onPageFinished}.
     */
    static final String INSTALL_HOOKS =
            "(function(){"
                    + "if(window.__tvdyPumpHooked)return;window.__tvdyPumpHooked=true;"
                    + "try{"
                    + "var meta=document.querySelector('meta[name=viewport]');"
                    + "if(!meta){meta=document.createElement('meta');meta.name='viewport';(document.head||document.documentElement).appendChild(meta);}"
                    + "meta.content='width=1280,initial-scale=1';"
                    + "}catch(e){}"
                    + "try{"
                    + "var RealAC=window.AudioContext||window.webkitAudioContext;"
                    + "if(RealAC){"
                    + "var patchedResume=function(){try{this.suspend();}catch(e){}return Promise.resolve();};"
                    + "RealAC.prototype.resume=patchedResume;"
                    + "function PatchedAC(){"
                    + "var ctx=new RealAC();"
                    + "try{ctx.suspend();}catch(e){}"
                    + "return ctx;"
                    + "}"
                    + "PatchedAC.prototype=RealAC.prototype;"
                    + "window.AudioContext=PatchedAC;"
                    + "if(window.webkitAudioContext)window.webkitAudioContext=PatchedAC;"
                    + "}"
                    + "}catch(e){}"
                    + "function neutralizeVideos(){"
                    + "try{document.querySelectorAll('video,audio').forEach(function(v){"
                    + "try{v.pause();}catch(e){}"
                    + "try{v.autoplay=false;v.removeAttribute('autoplay');}catch(e){}"
                    + "try{v.muted=true;v.volume=0;}catch(e){}"
                    + "try{if(v.getAttribute('src')){v.removeAttribute('src');v.load();}}catch(e){}"
                    + "});}catch(e){}"
                    + "}"
                    + "var __ntzScheduled=false;"
                    + "function neutralizeVideosDebounced(){"
                    + "if(__ntzScheduled)return;"
                    + "__ntzScheduled=true;"
                    + "setTimeout(function(){__ntzScheduled=false;neutralizeVideos();},500);"
                    + "}"
                    + "setInterval(neutralizeVideos,1000);"
                    + "neutralizeVideos();"
                    + "function isApiUrl(url){"
                    + "return /aweme\\/v\\d+\\/(web|pc)\\//.test(String(url||''))"
                    + "||/\\/aweme\\/v\\d+\\//.test(String(url||''));"
                    + "}"
                    + "function shouldReport(url,text){"
                    + "var u=String(url||'');"
                    + "var body=String(text||'');"
                    + "if(body.indexOf('\"aweme_list\"')>=0)return true;"
                    + "return /\\/aweme\\/v\\d+\\/(web|pc)\\/[^?]*feed/i.test(u)"
                    + "||/\\/aweme\\/v\\d+\\/(web|pc)\\/module\\/feed/i.test(u)"
                    + "||/\\/aweme\\/v\\d+\\/(web|pc)\\/tab\\/feed/i.test(u)"
                    + "||/\\/aweme\\/v\\d+\\/(web|pc)\\/(aweme\\/(post|related|detail)|general\\/search)/i.test(u);"
                    + "}"
                    + "function seen(url,note){"
                    + "try{if(isApiUrl(url)&&window.AndroidBridge){window.AndroidBridge.onUrlSeen(String(url),String(note||''));}}catch(e){}"
                    + "}"
                    + "function report(url,text){"
                    + "try{"
                    + "var body=String(text||'');"
                    + "if(!body)return;"
                    + "if(body.indexOf('\"aweme_list\"')>=0&&window.AndroidBridge){"
                    + "window.AndroidBridge.onFeedData(String(url||'body'),body);"
                    + "return;"
                    + "}"
                    + "if(shouldReport(url,body)&&window.AndroidBridge){"
                    + "window.AndroidBridge.onFeedData(String(url),body);"
                    + "}"
                    + "}catch(e){}"
                    + "}"
                    + "var originalFetch=window.fetch;"
                    + "if(originalFetch){"
                    + "window.fetch=function(){"
                    + "var args=arguments;"
                    + "return originalFetch.apply(this,args).then(function(resp){"
                    + "try{"
                    + "var input=args[0];"
                    + "var url=(input&&input.url)?input.url:input;"
                    + "seen(url,'fetch status='+resp.status);"
                    + "resp.clone().text().then(function(text){report(url,text);}).catch(function(err){seen(url,'fetch body read failed: '+err);});"
                    + "}catch(e){}"
                    + "return resp;"
                    + "});"
                    + "};"
                    + "}"
                    + "var XHROpen=XMLHttpRequest.prototype.open;"
                    + "var XHRSend=XMLHttpRequest.prototype.send;"
                    + "XMLHttpRequest.prototype.open=function(method,url){"
                    + "this.__tvdyUrl=url;"
                    + "return XHROpen.apply(this,arguments);"
                    + "};"
                    + "XMLHttpRequest.prototype.send=function(){"
                    + "var xhr=this;"
                    + "xhr.addEventListener('load',function(){"
                    + "try{"
                    + "var url=xhr.__tvdyUrl;"
                    + "var rt=xhr.responseType;"
                    + "seen(url,'xhr status='+xhr.status+' responseType='+JSON.stringify(rt));"
                    + "if(rt===''||rt==='text'){"
                    + "report(url,xhr.responseText);"
                    + "}else if(rt==='json'){"
                    + "try{report(url,JSON.stringify(xhr.response));}catch(e){seen(url,'json stringify failed');}"
                    + "}else if(rt==='arraybuffer'){"
                    + "try{report(url,new TextDecoder('utf-8').decode(new Uint8Array(xhr.response)));}catch(e){seen(url,'arraybuffer decode failed');}"
                    + "}else if(rt==='blob'){"
                    + "try{"
                    + "var reader=new FileReader();"
                    + "reader.onload=function(){try{report(url,String(reader.result||''));}catch(e){}};"
                    + "reader.readAsText(xhr.response);"
                    + "}catch(e){seen(url,'blob read failed');}"
                    + "}"
                    + "}catch(e){}"
                    + "});"
                    + "return XHRSend.apply(this,arguments);"
                    + "};"
                    + "function installObserver(){"
                    + "try{"
                    + "if(document.documentElement){"
                    + "new MutationObserver(neutralizeVideosDebounced).observe(document.documentElement,{childList:true,subtree:true});"
                    + "console.log('tvdy-pump hooks installed');"
                    + "}else{setTimeout(installObserver,50);}"
                    + "}catch(e){console.log('tvdy-pump observer install failed: '+e);}"
                    + "}"
                    + "installObserver();"
                    + "})();";

    /** Reports viewport size and whether the page looks like a login/captcha wall. */
    static final String PROBE_PAGE_STATE =
            "(function(){"
                    + "try{"
                    + "var body=(document.body&&document.body.innerText)||'';"
                    + "var info={"
                    + "w:window.innerWidth,h:window.innerHeight,"
                    + "title:document.title||'',"
                    + "hooked:!!window.__tvdyPumpHooked,"
                    + "videos:document.querySelectorAll('video').length,"
                    + "loginHint:body.indexOf('\\u767b\\u5f55')>=0||body.indexOf('\\u626b\\u7801')>=0,"
                    + "captchaHint:body.indexOf('\\u9a8c\\u8bc1')>=0"
                    + "};"
                    + "if(window.AndroidBridge){window.AndroidBridge.onPageProbe(JSON.stringify(info));}"
                    + "}catch(e){"
                    + "try{if(window.AndroidBridge){window.AndroidBridge.onPageProbe(JSON.stringify({error:String(e)}));}}catch(x){}"
                    + "}"
                    + "})();";

    /**
     * Nudge douyin's page into loading the recommend feed: fix viewport,
     * click the recommend tab if present, then simulate scroll/key.
     */
    static final String TRIGGER_INITIAL_FEED =
            "(function(){"
                    + "try{"
                    + "var meta=document.querySelector('meta[name=viewport]');"
                    + "if(!meta){meta=document.createElement('meta');meta.name='viewport';(document.head||document.documentElement).appendChild(meta);}"
                    + "meta.content='width=1280,initial-scale=1';"
                    + "}catch(e){}"
                    + "try{"
                    + "var nodes=document.querySelectorAll('a,span,div,button');"
                    + "for(var i=0;i<nodes.length&&i<300;i++){"
                    + "var t=(nodes[i].innerText||'').trim();"
                    + "if(t==='\\u63a8\\u8350'||t==='\\u9996\\u9875'){nodes[i].click();break;}"
                    + "}"
                    + "}catch(e){}"
                    + "function fire(type){"
                    + "var e=new KeyboardEvent(type,{key:'ArrowDown',code:'ArrowDown',keyCode:40,which:40,bubbles:true,cancelable:true});"
                    + "var t=document.activeElement||document.body||document.documentElement;"
                    + "try{t.dispatchEvent(e);}catch(err){}"
                    + "try{document.dispatchEvent(e);}catch(err){}"
                    + "try{window.dispatchEvent(e);}catch(err){}"
                    + "}"
                    + "fire('keydown');"
                    + "setTimeout(function(){fire('keyup');},30);"
                    + "setTimeout(function(){"
                    + "var amount=Math.max(window.innerHeight||720,document.documentElement.clientHeight||720,720);"
                    + "try{window.scrollBy({top:amount,behavior:'auto'});}catch(err){window.scrollBy(0,amount);}"
                    + "try{window.scrollTo(0,amount);}catch(err){}"
                    + "},150);"
                    + "})();";

    static final String REQUEST_NEXT_PAGE = TRIGGER_INITIAL_FEED;
}
